# Generated by Django 5.0.3 on 2024-03-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=32, unique=True)),
                ('bad_password', models.TextField(max_length=32, null=True)),
                ('email', models.TextField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='globaltools.useraccount')),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
    ]
