# Generated by Django 5.0.3 on 2024-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globaltools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='bad_password',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.TextField(max_length=32, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='password',
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
