# Generated by Django 5.0.3 on 2024-03-19 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globaltools', '0002_rename_bad_password_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='currency',
            field=models.CharField(choices=[('USD', 'American Dollar'), ('GBP', 'Pound Sterling'), ('EUR', 'Euro')], default='GBP', max_length=3),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Value (as outgoing)')),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='globaltools.holding')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_from', to='globaltools.holding')),
            ],
        ),
    ]
