# Generated by Django 5.0.3 on 2024-03-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('register', '0001_initial'), ('register', '0002_alter_account_password')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
