# Generated by Django 5.0.3 on 2024-03-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_0001-squish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='register.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.AddField(
            model_name='account',
            name='bad_password',
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.TextField(max_length=32, unique=True),
        ),
    ]
