# Generated by Django 5.0.4 on 2024-04-30 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payapp.transaction')),
            ],
        ),
    ]
