# Generated by Django 5.0.4 on 2024-04-30 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='id',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PEN', 'pending'), ('ACC', 'accepted'), ('REJ', 'rejected')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='request',
            name='transaction_requested',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='payapp.transaction'),
        ),
    ]
