# Generated by Django 5.0.4 on 2024-05-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user notified',
            new_name='user',
        ),
    ]
