# Generated by Django 5.0.4 on 2024-05-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_remove_request_id_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PEN', 'pending'), ('ACC', 'accepted'), ('REJ', 'rejected'), ('WIT', 'withdrawn')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='request',
            name='transaction_requested',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payapp.transaction'),
        ),
    ]
