# Generated by Django 5.0.4 on 2024-05-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_rename_user_notified_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='Nothing happened', max_length=256),
        ),
    ]
