# Generated by Django 5.0.4 on 2024-05-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='balance',
            field=models.FloatField(),
        ),
    ]
