# Generated by Django 5.0.4 on 2024-05-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_alter_holding_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractmoneymovement',
            name='value',
            field=models.FloatField(verbose_name='Value (as sent)'),
        ),
    ]
